name: Countries PHP

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    paths:
      - ".github/workflows/*.yml"
      - "data/**"
      - "dist/*.php"
      - "test/*.php"
      - "*.js"
      - "*.json"
      - "*.ts"
      - "!.editorconfig"
      - "!.travis.yml"
      - "!**LICENSE*"
      - "!**README*"

jobs:
  phpunit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: php-actions/composer@v5

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v2
        with:
          configuration: phpunit.xml
          args: --coverage-text
